" Name:         Essential Dev
" Author:       João Pesce <joao@pesce.cc>
" Maintainer:   João Pesce <joao@pesce.cc>
" License:      Vim License (see `:help license`)
" Last Updated: Tue Sep  1 20:41:47 2020

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'essential_dev'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#1a1d23', '#e06c75', '#98c379', '#e5c07b',
        \ '#61afef', '#c678dd', '#56b6c2', '#abb2bf', '#767676', '#ff6400',
        \ '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#e0e0ed']
  hi Terminal guifg=#abb2bf guibg=#1a1d23 guisp=NONE gui=NONE cterm=NONE
  hi! link lCursor Cursor
  hi! link Conditional Normal
  hi! link Label Normal
  hi! link Exception Normal
  hi! link Operator Normal
  hi! link Repeat Normal
  hi! link StorageClass Normal
  hi! link Structure Normal
  hi! link Typedef Normal
  hi! link Debug Normal
  hi! link Delimiter Normal
  hi! link SpecialChar Normal
  hi! link SpecialComment Normal
  hi! link Tag Normal
  hi! link Function Normal
  hi! link PopupSelected Normal
  hi! link QuickFixLine Normal
  hi! link Special Normal
  hi! link Constant Normal
  hi! link Type Normal
  hi Constant guifg=#56b6c2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Float Constant
  hi! link Number Constant
  hi! link Character Constant
  hi! link String Constant
  hi Statement guifg=#abb2bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link Keyword Statement
  hi! link Identifier Statement
  hi! link jsonKeyword Keyword
  hi! link cssClassName Identifier
  hi PreProc guifg=#abb2bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi PMenu guifg=#767676 guibg=#242424 guisp=NONE gui=NONE cterm=NONE
  hi PMenuSel guifg=NONE guibg=#464646 guisp=NONE gui=NONE cterm=NONE
  hi PMenuSbar guifg=#242424 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PMenuThumb guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#464646 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel guifg=#abb2bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#abb2bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#242424 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#abb2bf guibg=#242424 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#61afef guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#abb2bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Error guifg=#e06c75 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ErrorMsg Error
  hi! link diffRemoved Error
  hi WarningMsg guifg=#e5c07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#1a1d23 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#464646 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#abb2bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#464646 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link SignColumn LineNr
  hi! link FoldColumn LineNr
  hi IncSearch guifg=#e5c07b guibg=#767676 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#1a1d23 guibg=#e5c07b guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#464646 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#242424 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VertSplit StatusLine
  hi Visual guifg=NONE guibg=#242424 guisp=NONE gui=NONE cterm=NONE
  hi! link CursorLine Visual
  hi! link CursorLineNR Visual
  hi! link CursorColumn Visual
  hi! link ColorColumn Visual
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Folded guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi diffAdded guifg=#98c379 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e5c07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#56b6c2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  unlet s:t_Co
  finish
endif

if s:t_Co >= 256
  hi Terminal ctermfg=7 ctermbg=0 cterm=NONE
  hi! link lCursor Cursor
  hi! link Conditional Normal
  hi! link Label Normal
  hi! link Exception Normal
  hi! link Operator Normal
  hi! link Repeat Normal
  hi! link StorageClass Normal
  hi! link Structure Normal
  hi! link Typedef Normal
  hi! link Debug Normal
  hi! link Delimiter Normal
  hi! link SpecialChar Normal
  hi! link SpecialComment Normal
  hi! link Tag Normal
  hi! link Function Normal
  hi! link PopupSelected Normal
  hi! link QuickFixLine Normal
  hi! link Special Normal
  hi! link Constant Normal
  hi! link Type Normal
  hi Constant ctermfg=6 ctermbg=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Float Constant
  hi! link Number Constant
  hi! link Character Constant
  hi! link String Constant
  hi Statement ctermfg=7 ctermbg=NONE cterm=bold
  hi! link Keyword Statement
  hi! link Identifier Statement
  hi! link jsonKeyword Keyword
  hi! link cssClassName Identifier
  hi PreProc ctermfg=7 ctermbg=NONE cterm=bold
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi PMenu ctermfg=8 ctermbg=236 cterm=NONE
  hi PMenuSel ctermfg=NONE ctermbg=236 cterm=NONE
  hi PMenuSbar ctermfg=236 ctermbg=NONE cterm=NONE
  hi PMenuThumb ctermfg=8 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=236 ctermbg=NONE cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=7 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=7 ctermbg=NONE cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=7 ctermbg=236 cterm=NONE
  hi Question ctermfg=4 ctermbg=NONE cterm=NONE
  hi Title ctermfg=7 ctermbg=NONE cterm=bold
  hi Error ctermfg=1 ctermbg=NONE cterm=NONE
  hi! link ErrorMsg Error
  hi! link diffRemoved Error
  hi WarningMsg ctermfg=3 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=0 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=236 ctermbg=NONE cterm=NONE
  hi Normal ctermfg=7 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=8 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=236 ctermbg=NONE cterm=NONE
  hi! link SignColumn LineNr
  hi! link FoldColumn LineNr
  hi IncSearch ctermfg=3 ctermbg=8 cterm=NONE
  hi Search ctermfg=0 ctermbg=3 cterm=NONE
  hi StatusLine ctermfg=236 ctermbg=NONE cterm=NONE
  hi StatusLineNC ctermfg=236 ctermbg=NONE cterm=NONE
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VertSplit StatusLine
  hi Visual ctermfg=NONE ctermbg=236 cterm=NONE
  hi! link CursorLine Visual
  hi! link CursorLineNR Visual
  hi! link CursorColumn Visual
  hi! link ColorColumn Visual
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=underline
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=2 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=3 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=6 ctermbg=NONE cterm=NONE
  unlet s:t_Co
  finish
endif

if s:t_Co >= 8
  hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi! link lCursor Cursor
  hi! link Conditional Normal
  hi! link Label Normal
  hi! link Exception Normal
  hi! link Operator Normal
  hi! link Repeat Normal
  hi! link StorageClass Normal
  hi! link Structure Normal
  hi! link Typedef Normal
  hi! link Debug Normal
  hi! link Delimiter Normal
  hi! link SpecialChar Normal
  hi! link SpecialComment Normal
  hi! link Tag Normal
  hi! link Function Normal
  hi! link PopupSelected Normal
  hi! link QuickFixLine Normal
  hi! link Special Normal
  hi! link Constant Normal
  hi! link Type Normal
  hi Constant ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Float Constant
  hi! link Number Constant
  hi! link Character Constant
  hi! link String Constant
  hi Statement ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi! link Keyword Statement
  hi! link Identifier Statement
  hi! link jsonKeyword Keyword
  hi! link cssClassName Identifier
  hi PreProc ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi PMenu ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi PMenuSel ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi PMenuSbar ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi PMenuThumb ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi Question ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi Error ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi! link ErrorMsg Error
  hi! link diffRemoved Error
  hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi! link SignColumn LineNr
  hi! link FoldColumn LineNr
  hi IncSearch ctermfg=DarkYellow ctermbg=DarkGrey cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi StatusLine ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi StatusLineNC ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VertSplit StatusLine
  hi Visual ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi! link CursorLine Visual
  hi! link CursorLineNR Visual
  hi! link CursorColumn Visual
  hi! link ColorColumn Visual
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=underline
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Directory ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  unlet s:t_Co
  finish
endif

" Background: dark
" Color: black         #1a1d23                 00          Black
" Color: red           #e06c75                 01          DarkRed
" Color: green         #98c379                 02          DarkGreen
" Color: yellow        #e5c07b                 03          DarkYellow
" Color: blue          #61afef                 04          DarkBlue
" Color: magenta       #c678dd                 05          DarkMagenta
" Color: cyan          #56b6c2                 06          DarkCyan
" Color: white         #abb2bf                 07          LightGrey
" Color: brightblack   #767676                 08          DarkGrey
" Color: brightred     rgb(255, 100,   0)      09          LightRed
" Color: brightgreen   rgb(100, 255,   0)      10          LightGreen
" Color: brightyellow  rgb(255, 255, 100)      11          LightYellow
" Color: brightblue    rgb(  0, 100, 255)      12          LightBlue
" Color: brightmagenta rgb(255, 100, 255)      13          LightMagenta
" Color: brightcyan    rgb(100, 255, 255)      14          LightCyan
" Color: brightwhite   #e0e0ed                 15          White
" Color: almostblack   #242424                 236         DarkGrey
" Color: darkgray      #464646                 236         DarkGrey
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
